### ISSUE TITLE
Small bug in main.py

### ISSUE THREAD

**Issue by CaelynCheung1996** [yanivnik/sinfusion-code#24]
Line 63 in `main.py`, ` crop_size = (int(frames[0].shape[-2] * 0.95), int(frames[0].shape[-1:] * 0.95))` should be changed to `    crop_size = (int(frames[0].shape[-2] * 0.95), int(frames[0].shape[-1] * 0.95))`.

**Comment by yanivnik** [comment]
Thanks for noticing! Fixed.
