### ISSUE TITLE
About NNFDIV

### ISSUE THREAD

**Issue by zhangXJ147** [yanivnik/sinfusion-code#27]
Thanks for your great work about single image generation. 
Could you release the code of NNFDIV? Thanks.

**Comment by nivha** [comment]
Hi @zhangXJ147,

Thanks for asking. we will try to add it soon.

Niv

**Comment by nivha** [comment]
Dear @zhangXJ147,

Please check https://github.com/nivha/nnf_diversity

Niv

**Comment by zhangXJ147** [comment]
@nivha 
I got it. Thank you!
